unit Dext.Entity.Dialect.Firebird.Test;

interface

uses
  System.SysUtils,
  System.TypInfo,
  Dext.Entity.Dialects,
  Dext.Entity.Attributes;

type
  TFirebirdDialectTest = class
  private
    FDialect: TFirebirdDialect;
    procedure AssertEqual(const Expected, Actual, Msg: string);
    procedure Log(const Msg: string);
  public
    constructor Create;
    destructor Destroy; override;
    procedure Run;
  end;

implementation

{ TFirebirdDialectTest }

constructor TFirebirdDialectTest.Create;
begin
  FDialect := TFirebirdDialect.Create;
end;

destructor TFirebirdDialectTest.Destroy;
begin
  FDialect.Free;
  inherited;
end;

procedure TFirebirdDialectTest.Log(const Msg: string);
begin
  WriteLn(Msg);
end;

procedure TFirebirdDialectTest.AssertEqual(const Expected, Actual, Msg: string);
begin
  if Expected = Actual then
    WriteLn('   ✅ ', Msg)
  else
  begin
    WriteLn('   ❌ ', Msg);
    WriteLn('      Expected: ', Expected);
    WriteLn('      Actual:   ', Actual);
  end;
end;

procedure TFirebirdDialectTest.Run;
begin
  Log('🔥 Testing Firebird Dialect');
  Log('---------------------------');

  // 1. Identifiers
  AssertEqual('"Users"', FDialect.QuoteIdentifier('Users'), 'QuoteIdentifier should add double quotes');

  // 2. Booleans
  AssertEqual('TRUE', FDialect.BooleanToSQL(True), 'BooleanToSQL(True) should be TRUE');
  AssertEqual('FALSE', FDialect.BooleanToSQL(False), 'BooleanToSQL(False) should be FALSE');

  // 3. Paging
  AssertEqual('SELECT * FROM Users OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY', FDialect.GeneratePaging('SELECT * FROM Users', 0, 10), 'Paging (Skip 0, Take 10)');
  AssertEqual('SELECT * FROM Users OFFSET 20 ROWS FETCH NEXT 50 ROWS ONLY', FDialect.GeneratePaging('SELECT * FROM Users', 20, 50), 'Paging (Skip 20, Take 50)');

  // 4. Column Types
  AssertEqual('INTEGER', FDialect.GetColumnType(TypeInfo(Integer)), 'Integer mapping');
  AssertEqual('BIGINT', FDialect.GetColumnType(TypeInfo(Int64)), 'Int64 mapping');
  AssertEqual('VARCHAR(255)', FDialect.GetColumnType(TypeInfo(string)), 'String mapping');
  AssertEqual('BOOLEAN', FDialect.GetColumnType(TypeInfo(Boolean)), 'Boolean mapping');
  AssertEqual('TIMESTAMP', FDialect.GetColumnType(TypeInfo(TDateTime)), 'DateTime mapping');
  AssertEqual('DOUBLE PRECISION', FDialect.GetColumnType(TypeInfo(Double)), 'Double mapping');
  AssertEqual('DECIMAL(18,4)', FDialect.GetColumnType(TypeInfo(Currency)), 'Currency mapping');
  
  // 5. AutoInc
  AssertEqual('INTEGER GENERATED BY DEFAULT AS IDENTITY', FDialect.GetColumnType(TypeInfo(Integer), True), 'AutoInc Integer should be IDENTITY');
  
  // 6. Last Insert ID
  AssertEqual('', FDialect.GetLastInsertIdSQL, 'Last Insert ID SQL should be empty (requires RETURNING)');

  // 7. Create Table
  AssertEqual('CREATE TABLE "Users" (Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);', 
    FDialect.GetCreateTableSQL('"Users"', 'Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'), 'Create Table SQL');

  // 8. UUID Support
  AssertEqual('CHAR(36)', FDialect.GetColumnType(TypeInfo(TGUID)), 'GUID mapping should be CHAR(36)');
end;

end.
