unit Dext.Entity.Dialect.Oracle.Test;

interface

uses
  System.SysUtils,
  System.TypInfo,
  Dext.Entity.Dialects,
  Dext.Entity.Attributes;

type
  TOracleDialectTest = class
  private
    FDialect: TOracleDialect;
    procedure AssertEqual(const Expected, Actual, Msg: string);
    procedure Log(const Msg: string);
  public
    constructor Create;
    destructor Destroy; override;
    procedure Run;
  end;

implementation

{ TOracleDialectTest }

constructor TOracleDialectTest.Create;
begin
  FDialect := TOracleDialect.Create;
end;

destructor TOracleDialectTest.Destroy;
begin
  FDialect.Free;
  inherited;
end;

procedure TOracleDialectTest.Log(const Msg: string);
begin
  WriteLn(Msg);
end;

procedure TOracleDialectTest.AssertEqual(const Expected, Actual, Msg: string);
begin
  if Expected = Actual then
    WriteLn('   ✅ ', Msg)
  else
  begin
    WriteLn('   ❌ ', Msg);
    WriteLn('      Expected: ', Expected);
    WriteLn('      Actual:   ', Actual);
  end;
end;

procedure TOracleDialectTest.Run;
begin
  Log('🔮 Testing Oracle Dialect');
  Log('-----------------------');

  // 1. Identifiers
  AssertEqual('"Users"', FDialect.QuoteIdentifier('Users'), 'QuoteIdentifier should add double quotes');

  // 2. Booleans
  AssertEqual('1', FDialect.BooleanToSQL(True), 'BooleanToSQL(True) should be 1');
  AssertEqual('0', FDialect.BooleanToSQL(False), 'BooleanToSQL(False) should be 0');

  // 3. Paging
  AssertEqual('SELECT * FROM (SELECT * FROM Users ORDER BY ID) WHERE ROWNUM <= 10', FDialect.GeneratePaging('SELECT * FROM Users ORDER BY ID', 0, 10), 'Paging (Skip 0, Take 10)');
  AssertEqual('SELECT * FROM (SELECT a.*, ROWNUM rnum FROM (SELECT * FROM Users ORDER BY ID) a WHERE ROWNUM <= 20) WHERE rnum > 10', FDialect.GeneratePaging('SELECT * FROM Users ORDER BY ID', 10, 10), 'Paging (Skip 10, Take 10)');
  
  // 4. Column Types
  AssertEqual('NUMBER(10)', FDialect.GetColumnType(TypeInfo(Integer)), 'Integer mapping');
  AssertEqual('NUMBER(19)', FDialect.GetColumnType(TypeInfo(Int64)), 'Int64 mapping');
  AssertEqual('VARCHAR2(255)', FDialect.GetColumnType(TypeInfo(string)), 'String mapping');
  AssertEqual('NUMBER(1)', FDialect.GetColumnType(TypeInfo(Boolean)), 'Boolean mapping');
  AssertEqual('TIMESTAMP', FDialect.GetColumnType(TypeInfo(TDateTime)), 'DateTime mapping');
  AssertEqual('BINARY_DOUBLE', FDialect.GetColumnType(TypeInfo(Double)), 'Double mapping');
  AssertEqual('NUMBER(19,4)', FDialect.GetColumnType(TypeInfo(Currency)), 'Currency mapping');
  
  // 5. AutoInc
  AssertEqual('NUMBER(10) GENERATED BY DEFAULT AS IDENTITY', FDialect.GetColumnType(TypeInfo(Integer), True), 'AutoInc Integer should be IDENTITY');
  
  // 6. Last Insert ID
  AssertEqual('', FDialect.GetLastInsertIdSQL, 'Last Insert ID SQL should be empty (requires RETURNING)');

  // 7. UUID Support
  AssertEqual('VARCHAR2(36)', FDialect.GetColumnType(TypeInfo(TGUID)), 'GUID mapping should be VARCHAR2(36)');
end;

end.
